name: avarra_forge
description: Desktop world-authoring application for AVARRA.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  avarra_core: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
