[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$outputPath = Join-Path $repositoryRoot 'AVARRA_MASTER_LLM_HANDOFF_v8.md'
$sourcePaths = @(
    'docs/AVARRA_CANONICAL_LLM_HANDOFF.md'
    'docs/AVARRA_DOCUMENTATION_REVIEW.md'
    'docs/AVARRA_GAME_FORGE_BOUNDARIES.md'
    'docs/AVARRA_SYSTEM_ARCHITECTURE.md'
    'docs/AVARRA_CORE_RUNTIME.md'
    'docs/AVARRA_CLIENT_PRESENTATION.md'
    'docs/AVARRA_STAGE_2B_RENDERER_VALIDATION.md'
    'docs/AVARRA_ISOMETRIC_GAMEPLAY.md'
    'docs/AVARRA_STAGE_3_ISOMETRIC_VALIDATION.md'
    'docs/AVARRA_WORLD_CONTENT_MODEL.md'
    'docs/AVARRA_MULTIPLAYER_SERVER.md'
    'docs/AVARRA_FORGE_ARCHITECTURE.md'
    'docs/AVARRA_AI_CREATOR_ARCHITECTURE.md'
    'docs/AVARRA_AI_CREATOR_TOOL_API.md'
    'docs/AVARRA_AI_AGENT_QUICKSTART.md'
    'docs/AVARRA_DART_FLUTTER_LEVERAGE.md'
    'docs/AVARRA_IMPLEMENTATION_ROADMAP.md'
    'docs/AVARRA_OPEN_DECISIONS.md'
    'docs/AVARRA_LLM_IMPLEMENTATION_PROMPT.md'
    'docs/adr/ADR-008-build-avarra-not-an-engine.md'
    'docs/adr/ADR-009-scene-bridge-boundary.md'
    'docs/adr/ADR-010-isometric-first-product-profile.md'
    'docs/adr/ADR-011-ai-friendly-creator-api.md'
    'docs/adr/ADR-012-native-pub-workspace.md'
    'docs/adr/ADR-013-uuid-v7-stable-identifiers.md'
    'docs/adr/ADR-014-initial-ecs-storage-model.md'
    'docs/adr/ADR-015-flutter-scene-stable-sdk-compatibility.md'
    'docs/adr/ADR-016-initial-thermion-renderer.md'
    'docs/adr/ADR-017-thermion-windows-runtime-compatibility.md'
)

$sections = foreach ($relativePath in $sourcePaths) {
    $fullPath = Join-Path $repositoryRoot $relativePath
    if (-not (Test-Path -LiteralPath $fullPath -PathType Leaf)) {
        throw "Missing handoff source: $relativePath"
    }

    $label = $relativePath -replace '^docs/', ''
    $content = (Get-Content -Raw -Encoding UTF8 -LiteralPath $fullPath).TrimEnd()
    $sourceDirectory = (Split-Path -Parent $relativePath) -replace '\\', '/'
    if ($sourceDirectory) {
        # Image links are relative to each source document, while the generated
        # handoff lives at the repository root.
        $content = $content -replace '\]\(images/', "]($sourceDirectory/images/"
    }

    @"
<!-- BEGIN $label -->

$content

<!-- END $label -->
"@
}

$header = @'
# AVARRA — MASTER LLM HANDOFF v8

This file is generated by `tool/build_master_handoff.ps1` for convenient
single-file handoff. Edit the individual source documents, then regenerate it.
'@

$result = $header.TrimEnd() + "`n`n---`n`n" + ($sections -join "`n`n---`n`n") + "`n`n---`n"
$encoding = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($outputPath, $result, $encoding)
